mlflow:
  url: https://bede-105-158-176-209.ngrok-free.app/
pushgateway:
  url: https://dce0-105-158-176-209.ngrok-free.app
prometheus:
  url: https://9239-105-158-176-209.ngrok-free.app
data:
  file_name: lstm_predictions_charger.csv
  file_path: 1fJM376Icrrs9Ww86IN4-4DJw2w-faLoO
