version: '3'
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - "/d/PFE/Repo_ML/Backend/prometheus.yml:/etc/prometheus/prometheus.yml"  # Remplace par ton chemin absolu correct
    restart: always

  pushgateway:
    image: prom/pushgateway
    container_name: pushgateway
    ports:
      - "9091:9091"
    restart: always
